package relay.nodes;

public enum RelayNodeType {
	ROOT, BLOCK, EXPRESSION, VARIABLE_ACCESS, BLOCK_PROPERTY, CODE_BLOCK, FUNCTION_CALL_EXPRESSION, CODE_STATEMENT, VARIABLE_DEFINITION, REPEAT_DEFINITION, 
}
