
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package parser;

import java_cup.runtime.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20150326 (SVN rev 63) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class RelayParser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return RelaySymbols.class;
}

  /** Default constructor. */
  @Deprecated
  public RelayParser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public RelayParser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public RelayParser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\032\000\002\002\004\000\002\002\003\000\002\003" +
    "\007\000\002\003\006\000\002\005\002\000\002\005\004" +
    "\000\002\006\004\000\002\006\004\000\002\006\004\000" +
    "\002\006\003\000\002\014\005\000\002\015\004\000\002" +
    "\015\003\000\002\016\017\000\002\007\005\000\002\010" +
    "\004\000\002\010\005\000\002\010\005\000\002\010\003" +
    "\000\002\010\003\000\002\013\006\000\002\012\005\000" +
    "\002\012\003\000\002\011\003\000\002\011\003\000\002" +
    "\004\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\073\000\004\012\005\001\002\000\004\002\075\001" +
    "\002\000\006\004\011\010\010\001\002\000\004\002\000" +
    "\001\002\000\004\004\072\001\002\000\020\004\uffe8\006" +
    "\uffe8\007\uffe8\011\uffe8\013\uffe8\020\uffe8\021\uffe8\001\002" +
    "\000\014\004\ufffd\010\ufffd\012\ufffd\013\ufffd\014\ufffd\001" +
    "\002\000\014\004\021\010\010\012\005\013\016\014\017" +
    "\001\002\000\004\006\052\001\002\000\014\004\ufffc\010" +
    "\ufffc\012\ufffc\013\ufffc\014\ufffc\001\002\000\004\004\051" +
    "\001\002\000\006\002\ufffe\004\ufffe\001\002\000\004\022" +
    "\027\001\002\000\004\004\024\001\002\000\014\004\ufff8" +
    "\010\ufff8\012\ufff8\013\ufff8\014\ufff8\001\002\000\004\004" +
    "\023\001\002\000\014\004\ufff9\010\ufff9\012\ufff9\013\ufff9" +
    "\014\ufff9\001\002\000\014\004\ufffa\010\ufffa\012\ufffa\013" +
    "\ufffa\014\ufffa\001\002\000\006\015\ufff5\022\027\001\002" +
    "\000\004\015\047\001\002\000\004\023\030\001\002\000" +
    "\004\012\031\001\002\000\004\010\010\001\002\000\004" +
    "\011\036\001\002\000\016\004\uffeb\007\034\011\uffeb\013" +
    "\uffeb\020\uffeb\021\uffeb\001\002\000\004\010\010\001\002" +
    "\000\014\004\uffec\011\uffec\013\uffec\020\uffec\021\uffec\001" +
    "\002\000\004\010\010\001\002\000\004\013\040\001\002" +
    "\000\004\024\041\001\002\000\004\012\042\001\002\000" +
    "\004\010\010\001\002\000\004\011\044\001\002\000\004" +
    "\010\010\001\002\000\004\013\046\001\002\000\006\015" +
    "\ufff4\022\ufff4\001\002\000\004\004\ufff7\001\002\000\004" +
    "\015\ufff6\001\002\000\014\004\ufffb\010\ufffb\012\ufffb\013" +
    "\ufffb\014\ufffb\001\002\000\006\005\054\010\055\001\002" +
    "\000\010\004\uffef\020\uffef\021\uffef\001\002\000\006\016" +
    "\067\017\071\001\002\000\014\004\uffe8\007\uffe8\012\064" +
    "\020\uffe8\021\uffe8\001\002\000\010\004\ufff3\020\061\021" +
    "\060\001\002\000\010\004\uffee\020\uffee\021\uffee\001\002" +
    "\000\006\005\054\010\055\001\002\000\006\005\054\010" +
    "\055\001\002\000\010\004\ufff1\020\ufff1\021\ufff1\001\002" +
    "\000\010\004\ufff0\020\ufff0\021\ufff0\001\002\000\004\010" +
    "\010\001\002\000\004\013\066\001\002\000\010\004\uffed" +
    "\020\uffed\021\uffed\001\002\000\010\004\uffea\020\uffea\021" +
    "\uffea\001\002\000\010\004\ufff2\020\ufff2\021\ufff2\001\002" +
    "\000\010\004\uffe9\020\uffe9\021\uffe9\001\002\000\014\004" +
    "\ufffd\010\ufffd\012\ufffd\013\ufffd\014\ufffd\001\002\000\014" +
    "\004\021\010\010\012\005\013\074\014\017\001\002\000" +
    "\006\002\uffff\004\uffff\001\002\000\004\002\001\001\002" +
    "" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\073\000\006\002\003\003\005\001\001\000\002\001" +
    "\001\000\004\004\006\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\005\011\001\001\000" +
    "\014\003\014\004\012\006\013\007\017\014\021\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\006\015\025\016\024\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\006\015\047\016\024\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\006\004\032\012\031\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\004\032\012\034\001\001\000\002\001" +
    "\001\000\006\004\032\012\036\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\006\004\032\012" +
    "\042\001\001\000\002\001\001\000\006\004\032\012\044" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\012\004\032" +
    "\010\055\012\052\013\056\001\001\000\002\001\001\000" +
    "\004\011\067\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\012\004\032\010\062\012\052\013" +
    "\056\001\001\000\012\004\032\010\061\012\052\013\056" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\004" +
    "\032\012\064\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\005\072\001\001\000\014\003\014\004\012\006\013" +
    "\007\017\014\021\001\001\000\002\001\001\000\002\001" +
    "\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$RelayParser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$RelayParser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$RelayParser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$RelayParser$actions {
  private final RelayParser parser;

  /** Constructor */
  CUP$RelayParser$actions(RelayParser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$RelayParser$do_action_part00000000(
    int                        CUP$RelayParser$act_num,
    java_cup.runtime.lr_parser CUP$RelayParser$parser,
    java.util.Stack            CUP$RelayParser$stack,
    int                        CUP$RelayParser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$RelayParser$result;

      /* select the action based on the action number */
      switch (CUP$RelayParser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= goal EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$RelayParser$stack.elementAt(CUP$RelayParser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$RelayParser$stack.elementAt(CUP$RelayParser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$RelayParser$stack.elementAt(CUP$RelayParser$top-1)).value;
		RESULT = start_val;
              CUP$RelayParser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$RelayParser$stack.elementAt(CUP$RelayParser$top-1)), ((java_cup.runtime.Symbol)CUP$RelayParser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$RelayParser$parser.done_parsing();
          return CUP$RelayParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // goal ::= block 
            {
              Object RESULT =null;

              CUP$RelayParser$result = parser.getSymbolFactory().newSymbol("goal",0, ((java_cup.runtime.Symbol)CUP$RelayParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$RelayParser$stack.peek()), RESULT);
            }
          return CUP$RelayParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // block ::= BLOCK_OPEN identifyer NEW_LINE block_content_list BLOCK_CLOSE 
            {
              Object RESULT =null;

              CUP$RelayParser$result = parser.getSymbolFactory().newSymbol("block",1, ((java_cup.runtime.Symbol)CUP$RelayParser$stack.elementAt(CUP$RelayParser$top-4)), ((java_cup.runtime.Symbol)CUP$RelayParser$stack.peek()), RESULT);
            }
          return CUP$RelayParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // block ::= BLOCK_OPEN NEW_LINE block_content_list BLOCK_CLOSE 
            {
              Object RESULT =null;

              CUP$RelayParser$result = parser.getSymbolFactory().newSymbol("block",1, ((java_cup.runtime.Symbol)CUP$RelayParser$stack.elementAt(CUP$RelayParser$top-3)), ((java_cup.runtime.Symbol)CUP$RelayParser$stack.peek()), RESULT);
            }
          return CUP$RelayParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // block_content_list ::= 
            {
              Object RESULT =null;

              CUP$RelayParser$result = parser.getSymbolFactory().newSymbol("block_content_list",3, ((java_cup.runtime.Symbol)CUP$RelayParser$stack.peek()), RESULT);
            }
          return CUP$RelayParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // block_content_list ::= block_content_list block_content_item 
            {
              Object RESULT =null;

              CUP$RelayParser$result = parser.getSymbolFactory().newSymbol("block_content_list",3, ((java_cup.runtime.Symbol)CUP$RelayParser$stack.elementAt(CUP$RelayParser$top-1)), ((java_cup.runtime.Symbol)CUP$RelayParser$stack.peek()), RESULT);
            }
          return CUP$RelayParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // block_content_item ::= block NEW_LINE 
            {
              Object RESULT =null;

              CUP$RelayParser$result = parser.getSymbolFactory().newSymbol("block_content_item",4, ((java_cup.runtime.Symbol)CUP$RelayParser$stack.elementAt(CUP$RelayParser$top-1)), ((java_cup.runtime.Symbol)CUP$RelayParser$stack.peek()), RESULT);
            }
          return CUP$RelayParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // block_content_item ::= block_property NEW_LINE 
            {
              Object RESULT =null;

              CUP$RelayParser$result = parser.getSymbolFactory().newSymbol("block_content_item",4, ((java_cup.runtime.Symbol)CUP$RelayParser$stack.elementAt(CUP$RelayParser$top-1)), ((java_cup.runtime.Symbol)CUP$RelayParser$stack.peek()), RESULT);
            }
          return CUP$RelayParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // block_content_item ::= code_block NEW_LINE 
            {
              Object RESULT =null;

              CUP$RelayParser$result = parser.getSymbolFactory().newSymbol("block_content_item",4, ((java_cup.runtime.Symbol)CUP$RelayParser$stack.elementAt(CUP$RelayParser$top-1)), ((java_cup.runtime.Symbol)CUP$RelayParser$stack.peek()), RESULT);
            }
          return CUP$RelayParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // block_content_item ::= NEW_LINE 
            {
              Object RESULT =null;

              CUP$RelayParser$result = parser.getSymbolFactory().newSymbol("block_content_item",4, ((java_cup.runtime.Symbol)CUP$RelayParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$RelayParser$stack.peek()), RESULT);
            }
          return CUP$RelayParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // code_block ::= CODE_BLOCK_OPEN code_statement_list CODE_BLOCK_CLOSE 
            {
              Object RESULT =null;

              CUP$RelayParser$result = parser.getSymbolFactory().newSymbol("code_block",10, ((java_cup.runtime.Symbol)CUP$RelayParser$stack.elementAt(CUP$RelayParser$top-2)), ((java_cup.runtime.Symbol)CUP$RelayParser$stack.peek()), RESULT);
            }
          return CUP$RelayParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // code_statement_list ::= code_statement code_statement_list 
            {
              Object RESULT =null;

              CUP$RelayParser$result = parser.getSymbolFactory().newSymbol("code_statement_list",11, ((java_cup.runtime.Symbol)CUP$RelayParser$stack.elementAt(CUP$RelayParser$top-1)), ((java_cup.runtime.Symbol)CUP$RelayParser$stack.peek()), RESULT);
            }
          return CUP$RelayParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // code_statement_list ::= code_statement 
            {
              Object RESULT =null;

              CUP$RelayParser$result = parser.getSymbolFactory().newSymbol("code_statement_list",11, ((java_cup.runtime.Symbol)CUP$RelayParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$RelayParser$stack.peek()), RESULT);
            }
          return CUP$RelayParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // code_statement ::= KEYWORD_LINE KEYWORD_FROM BLOCK_OPEN variable_access COMMA variable_access BLOCK_CLOSE KEYWORD_TO BLOCK_OPEN variable_access COMMA variable_access BLOCK_CLOSE 
            {
              Object RESULT =null;

              CUP$RelayParser$result = parser.getSymbolFactory().newSymbol("code_statement",12, ((java_cup.runtime.Symbol)CUP$RelayParser$stack.elementAt(CUP$RelayParser$top-12)), ((java_cup.runtime.Symbol)CUP$RelayParser$stack.peek()), RESULT);
            }
          return CUP$RelayParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // block_property ::= identifyer COLON expression 
            {
              Object RESULT =null;

              CUP$RelayParser$result = parser.getSymbolFactory().newSymbol("block_property",5, ((java_cup.runtime.Symbol)CUP$RelayParser$stack.elementAt(CUP$RelayParser$top-2)), ((java_cup.runtime.Symbol)CUP$RelayParser$stack.peek()), RESULT);
            }
          return CUP$RelayParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // expression ::= NUMBER unit 
            {
              Object RESULT =null;

              CUP$RelayParser$result = parser.getSymbolFactory().newSymbol("expression",6, ((java_cup.runtime.Symbol)CUP$RelayParser$stack.elementAt(CUP$RelayParser$top-1)), ((java_cup.runtime.Symbol)CUP$RelayParser$stack.peek()), RESULT);
            }
          return CUP$RelayParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // expression ::= expression OPERATOR_PLUS expression 
            {
              Object RESULT =null;

              CUP$RelayParser$result = parser.getSymbolFactory().newSymbol("expression",6, ((java_cup.runtime.Symbol)CUP$RelayParser$stack.elementAt(CUP$RelayParser$top-2)), ((java_cup.runtime.Symbol)CUP$RelayParser$stack.peek()), RESULT);
            }
          return CUP$RelayParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // expression ::= expression OPERATOR_MINUS expression 
            {
              Object RESULT =null;

              CUP$RelayParser$result = parser.getSymbolFactory().newSymbol("expression",6, ((java_cup.runtime.Symbol)CUP$RelayParser$stack.elementAt(CUP$RelayParser$top-2)), ((java_cup.runtime.Symbol)CUP$RelayParser$stack.peek()), RESULT);
            }
          return CUP$RelayParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // expression ::= variable_access 
            {
              Object RESULT =null;

              CUP$RelayParser$result = parser.getSymbolFactory().newSymbol("expression",6, ((java_cup.runtime.Symbol)CUP$RelayParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$RelayParser$stack.peek()), RESULT);
            }
          return CUP$RelayParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // expression ::= function_call 
            {
              Object RESULT =null;

              CUP$RelayParser$result = parser.getSymbolFactory().newSymbol("expression",6, ((java_cup.runtime.Symbol)CUP$RelayParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$RelayParser$stack.peek()), RESULT);
            }
          return CUP$RelayParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // function_call ::= IDENTIFYER BLOCK_OPEN variable_access BLOCK_CLOSE 
            {
              Object RESULT =null;

              CUP$RelayParser$result = parser.getSymbolFactory().newSymbol("function_call",9, ((java_cup.runtime.Symbol)CUP$RelayParser$stack.elementAt(CUP$RelayParser$top-3)), ((java_cup.runtime.Symbol)CUP$RelayParser$stack.peek()), RESULT);
            }
          return CUP$RelayParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // variable_access ::= identifyer DOT variable_access 
            {
              Object RESULT =null;

              CUP$RelayParser$result = parser.getSymbolFactory().newSymbol("variable_access",8, ((java_cup.runtime.Symbol)CUP$RelayParser$stack.elementAt(CUP$RelayParser$top-2)), ((java_cup.runtime.Symbol)CUP$RelayParser$stack.peek()), RESULT);
            }
          return CUP$RelayParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // variable_access ::= identifyer 
            {
              Object RESULT =null;

              CUP$RelayParser$result = parser.getSymbolFactory().newSymbol("variable_access",8, ((java_cup.runtime.Symbol)CUP$RelayParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$RelayParser$stack.peek()), RESULT);
            }
          return CUP$RelayParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // unit ::= UNIT_PIXELS 
            {
              Object RESULT =null;

              CUP$RelayParser$result = parser.getSymbolFactory().newSymbol("unit",7, ((java_cup.runtime.Symbol)CUP$RelayParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$RelayParser$stack.peek()), RESULT);
            }
          return CUP$RelayParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // unit ::= UNIT_PERCENT 
            {
              Object RESULT =null;

              CUP$RelayParser$result = parser.getSymbolFactory().newSymbol("unit",7, ((java_cup.runtime.Symbol)CUP$RelayParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$RelayParser$stack.peek()), RESULT);
            }
          return CUP$RelayParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // identifyer ::= IDENTIFYER 
            {
              Object RESULT =null;

              CUP$RelayParser$result = parser.getSymbolFactory().newSymbol("identifyer",2, ((java_cup.runtime.Symbol)CUP$RelayParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$RelayParser$stack.peek()), RESULT);
            }
          return CUP$RelayParser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$RelayParser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$RelayParser$do_action(
    int                        CUP$RelayParser$act_num,
    java_cup.runtime.lr_parser CUP$RelayParser$parser,
    java.util.Stack            CUP$RelayParser$stack,
    int                        CUP$RelayParser$top)
    throws java.lang.Exception
    {
              return CUP$RelayParser$do_action_part00000000(
                               CUP$RelayParser$act_num,
                               CUP$RelayParser$parser,
                               CUP$RelayParser$stack,
                               CUP$RelayParser$top);
    }
}

}
