package parser;

//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PROPERTY_PROPERTIES = 19;
  public static final int KEYWORD_LINE = 28;
  public static final int IDENTIFYER = 6;
  public static final int ORIGIN_TOP_LEFT = 22;
  public static final int PROPERTY_HEIGHT = 13;
  public static final int BLOCK_OPEN = 8;
  public static final int PROPERTY_TOP = 15;
  public static final int PROPERTY_LEFT = 16;
  public static final int UNIT_PERCENT = 21;
  public static final int KEYWORD_FROM = 29;
  public static final int COLON = 4;
  public static final int NEW_LINE = 2;
  public static final int COMMA = 7;
  public static final int BLOCK_CLOSE = 9;
  public static final int PROPERTY_ORIGIN = 18;
  public static final int EOF = 0;
  public static final int NUMBER = 3;
  public static final int ORIGIN_TOP_RIGHT = 23;
  public static final int ORIGIN_BOTTOM_RIGHT = 25;
  public static final int CODE_BLOCK_CLOSE = 11;
  public static final int PROPERTY_WIDTH = 12;
  public static final int error = 1;
  public static final int DOT = 5;
  public static final int CODE_BLOCK_OPEN = 10;
  public static final int ORIGIN_BOTTOM_LEFT = 24;
  public static final int OPERATOR_MINUS = 27;
  public static final int OPERATOR_PLUS = 26;
  public static final int KEYWORD_TO = 30;
  public static final int PROPERTY_RIGHT = 17;
  public static final int PROPERTY_BOTTOM = 14;
  public static final int UNIT_PIXELS = 20;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NEW_LINE",
  "NUMBER",
  "COLON",
  "DOT",
  "IDENTIFYER",
  "COMMA",
  "BLOCK_OPEN",
  "BLOCK_CLOSE",
  "CODE_BLOCK_OPEN",
  "CODE_BLOCK_CLOSE",
  "PROPERTY_WIDTH",
  "PROPERTY_HEIGHT",
  "PROPERTY_BOTTOM",
  "PROPERTY_TOP",
  "PROPERTY_LEFT",
  "PROPERTY_RIGHT",
  "PROPERTY_ORIGIN",
  "PROPERTY_PROPERTIES",
  "UNIT_PIXELS",
  "UNIT_PERCENT",
  "ORIGIN_TOP_LEFT",
  "ORIGIN_TOP_RIGHT",
  "ORIGIN_BOTTOM_LEFT",
  "ORIGIN_BOTTOM_RIGHT",
  "OPERATOR_PLUS",
  "OPERATOR_MINUS",
  "KEYWORD_LINE",
  "KEYWORD_FROM",
  "KEYWORD_TO"
  };
}

