
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package relay.parser;

/** CUP generated class containing symbol constants. */
public class RelaySymbols {
  /* terminals */
  public static final int SEMICOLON = 4;
  public static final int IDENTIFYER = 8;
  public static final int OPERATOR_OF = 15;
  public static final int KEYWORD_IN = 18;
  public static final int BLOCK_OPEN = 9;
  public static final int UNIT_PERCENT = 12;
  public static final int COLON = 3;
  public static final int NEW_LINE = 2;
  public static final int COMMA = 6;
  public static final int BLOCK_CLOSE = 10;
  public static final int EOF = 0;
  public static final int NUMBER = 7;
  public static final int error = 1;
  public static final int DOT = 5;
  public static final int KEYWORD_DEF = 16;
  public static final int OPERATOR_PLUS = 13;
  public static final int OPERATOR_MINUS = 14;
  public static final int KEYWORD_FOR = 17;
  public static final int UNIT_PIXELS = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NEW_LINE",
  "COLON",
  "SEMICOLON",
  "DOT",
  "COMMA",
  "NUMBER",
  "IDENTIFYER",
  "BLOCK_OPEN",
  "BLOCK_CLOSE",
  "UNIT_PIXELS",
  "UNIT_PERCENT",
  "OPERATOR_PLUS",
  "OPERATOR_MINUS",
  "OPERATOR_OF",
  "KEYWORD_DEF",
  "KEYWORD_FOR",
  "KEYWORD_IN"
  };
}

