package relay.parser.symbols.types;

public enum RelaySymbolType {
	ROOT, 
	BLOCK,
	BLOCK_CONTENT_LIST_ITEM, 
	IDENTIFYER, 
	UNIT, 
	VARIABLE_ACCESS, 
	STATEMENT_LIST_NODE, 
	BLOCK_CONTENT_ITEM, 
	BLOCK_PROPERTY, 
	CODE_BLOCK, 
	CODE_STATEMENT, 
	EXPRESSION, 
	PARAMETER_LIST, 
}