package relay.parser.symbols.types;

public enum RelaySymbolType {
	ROOT, 
	BLOCK,
	BLOCK_CONTENT_LIST_ITEM, 
	BLOCK_PROPERTY, 
	BLOCK_CONTENT_ITEM, 
	BLOCK_DETAILS, 
	IDENTIFYER, 
	UNIT, 
	VARIABLE_ACCESS, 
	VARIABLE_DEFINITION, 
	EXPRESSION, 
	PARAMETER_LIST, 
	TOKEN, 
	REPEAT_DEFINITION, 
}